# This Dockerfile is available from:
#   https://github.com/docker-training/staticweb

FROM nginx:1.9.4

MAINTAINER Docker Education Team <education@docker.com>

RUN echo 'Hi my name is Tom, I am in your container' \
    >/usr/share/nginx/html/index.html

