# This Dockerfile is available from:
#   https://github.com/docker-training/staticweb

FROM nginx:1.9.4

MAINTAINER Docker Education Team <education@docker.com>

RUN echo 'Docker is awesome.' \
    >/usr/share/nginx/html/index.html

